### ISSUE TITLE
not working on Safari 15.1?

### ISSUE THREAD

**Issue by Grrrrrrrrrrrrrrrrrrrr** [jayluxferro/XDM-Browser-Extension#1]
Hi!

I've just installed your extension on Safari 15.1 under Monterey 12.0.1 and XDM 7.2.7.

While the extension is visible and has rights, it doesn't seem to connect to the servers (Vimeo or Youtube) to offer any options...

Can you check?

:-)

**Comment by jayluxferro** [comment]
Hi, I use Monterey with a compiled XDM 7.2.11. You can download it here https://github.com/jayluxferro/XDM-Browser-Extension/releases/download/v1.0.0/XDMSetup.dmg

![Screenshot 2021-11-10 at 05 22 32 (2)](https://user-images.githubusercontent.com/8394019/141065641-b9f30b33-50eb-4d70-8048-b1cd1e72e21d.png)
