### ISSUE TITLE
That's really a great app thanks

### ISSUE THREAD

**Issue by krushnadeore** [jayluxferro/XDM-Browser-Extension#2]
suggestion hope u add m1 support

**Comment by jayluxferro** [comment]
Thanks @krushnadeore . You can run it on the M1. It's a fat binary so it has two architectures: both intel and arm

**Comment by krushnadeore** [comment]
yeah I already using it on m1 running great any plan for update ?

**Comment by jayluxferro** [comment]
yeah I will. Trying to get my hands on an M1
