### ISSUE TITLE
No video downloadable options are showing

### ISSUE THREAD

**Issue by w99910** [jayluxferro/XDM-Browser-Extension#3]
- [x] Xdm and its extension are downloaded.
- [x] enable 'allow unsigned extension'

My Mac is m1 Monterey 12.1

<img width="1440" alt="Screen Shot 2022-01-14 at 3 15 16 PM" src="https://user-images.githubusercontent.com/65523475/149485220-03b8896f-4193-4f02-8738-57872b773641.png">

**Comment by jayluxferro** [comment]
@w99910 , did you enable the full permissions of the extension?



![Screenshot 2022-01-14 at 8 54 03 AM](https://user-images.githubusercontent.com/8394019/149487105-efa32167-6835-4731-b658-0d81d2fdaf69.png)
